# This rule is not used by the project injector-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to injector.zvelocity.gg resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: injector-operator
    app.kubernetes.io/managed-by: kustomize
  name: injector-viewer-role
rules:
- apiGroups:
  - injector.zvelocity.gg
  resources:
  - injectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - injector.zvelocity.gg
  resources:
  - injectors/status
  verbs:
  - get
