# This rule is not used by the project injector-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over injector.zvelocity.gg.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: injector-operator
    app.kubernetes.io/managed-by: kustomize
  name: injector-admin-role
rules:
- apiGroups:
  - injector.zvelocity.gg
  resources:
  - injectors
  verbs:
  - '*'
- apiGroups:
  - injector.zvelocity.gg
  resources:
  - injectors/status
  verbs:
  - get
